config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView
from django.views import defaults as default_views

from allauth.account.views import confirm_email

from nicolock.core.views import pages_router
from nicolock.core.sitemaps import sitemaps
from nicolock.users.views import FindContractors


urlpatterns = [
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^froala_editor/', include('froala_editor.urls')),

    url(
        regex=r'^$',
        view=TemplateView.as_view(template_name='pages/home.html'),
        name='home'
    ),

    url(
        regex=r'^contractors/$',
        view=FindContractors.as_view(),
        name='find-contractors'
    ),

    url(
        regex=r'^users/',
        view=include('nicolock.users.urls', namespace='users')
    ),
    url(
        regex=r'^accounts/',
        view=include('allauth.urls')
    ),
    url(
        regex=r'^rest-auth/registration/account-confirm-email/(?P<key>[-:\w]+)/$',
        view=confirm_email,
        name="account_confirm_email"
    ),
    url(
        regex=r'^rest-auth/',
        view=include('rest_auth.urls')
    ),
    url(
        regex=r'^rest-auth/registration/',
        view=include('rest_auth.registration.urls')
    ),

    url(
        regex=r'^rest/',
        view=include('nicolock.users.rest_urls', namespace='rest-users')
    ),
    url(
        regex=r'^rest/',
        view=include('nicolock.products.rest_urls', namespace='rest-products')
    ),
    url(
        regex=r'^rest/',
        view=include('nicolock.videos.rest_urls', namespace='rest-videos')
    ),
    url(
        regex=r'^rest/',
        view=include('nicolock.dealers.rest_urls', namespace='rest-dealers')
    ),
    url(
        regex=r'^rest/',
        view=include('nicolock.salesreps.rest_urls', namespace='rest-salesreps')
    ),
    url(
        regex=r'^rest/',
        view=include('nicolock.galleries.rest_urls', namespace='rest-galleries')
    ),
    url(
        regex=r'^rest/',
        view=include('nicolock.core.rest_urls', namespace='rest-core')
    ),
    url(
        regex=r'^rest/',
        view=include('nicolock.faqs.rest_urls', namespace='rest-faqs')
    ),
    url(
        regex=r'^rest/',
        view=include('nicolock.events.rest_urls', namespace='rest-events')
    ),
    url(
        regex=r'^products/',
        view=include('nicolock.products.urls', namespace='products')
    ),
    url(
        regex=r'^videos/',
        view=include('nicolock.videos.urls', namespace='videos')
    ),
    url(
        regex=r'^dealers/',
        view=include('nicolock.dealers.urls', namespace='dealers')
    ),
    url(
        regex=r'^faqs/',
        view=include('nicolock.faqs.urls', namespace='faqs')
    ),
    url(
        regex=r'^design-ideas/',
        view=include('nicolock.design.urls', namespace='design')
    ),
    url(
        regex=r'^image-library/',
        view=include('nicolock.library.urls', namespace='library')
    ),
    url(
        regex=r'^innovation/',
        view=include('nicolock.innovation.urls', namespace='innovation')
    ),

    url(
        regex=r'^',
        view=include('nicolock.galleries.urls', namespace='galleries')
    ),
    url(
        regex=r'^',
        view=include('nicolock.events.urls', namespace='events')
    ),

    url(
        regex=r'^',
        view=include('nicolock.core.urls', namespace='core')
    ),

    # Flat Pages/Landing Pages
    url(
        regex=r'^(?P<url>[-\w]+)/$',
        view=pages_router,
        name='pages'
    ),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Django sitemap
urlpatterns += [
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

nicolock/core/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^search/$',
        view=views.Search.as_view(),
        name='search'
    ),
    url(
        regex=r'^quote/$',
        view=views.Quote.as_view(),
        name='quote'
    ),
    url(
        regex=r'^contact/$',
        view=views.Contact.as_view(),
        name='contact'
    ),
    url(
        regex=r'^customer-service-request/$',
        view=views.CustomerServiceRequest.as_view(),
        name='customer-service-request'
    )
]

nicolock/faqs/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.FaqList.as_view(), name='list'),
]

nicolock/galleries/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^inspiration/$',
        view=views.InspirationList.as_view(),
        name='inspiration-list'
    ),
    url(
        regex=r'^inspiration/(?P<slug>[-\w]+)/$',
        view=views.InspirationDetail.as_view(),
        name='inspiration-detail'
    ),
    url(
        regex=r'^galleries/add/$',
        view=views.GalleryCreate.as_view(),
        name='gallery-add'
    ),
    url(
        regex=r'^projects/(?P<project_slug>[-\w]+)/gallery-add/$',
        view=views.GalleryCreate.as_view(),
        name='gallery-add-from-project'
    ),
    url(
        regex=r'^galleries/(?P<slug>[-\w]+)/$',
        view=views.GalleryDetail.as_view(),
        name='gallery-detail'
    ),
    url(
        regex=r'^galleries/(?P<slug>[-\w]+)/edit/$',
        view=views.GalleryUpdate.as_view(),
        name='gallery-edit'
    ),
    url(
        regex=r'^galleries/(?P<slug>[-\w]+)/delete/$',
        view=views.GalleryDelete.as_view(),
        name='gallery-delete'
    ),
    url(
        regex=r'^(?P<user_slug>[-\w]+)/projects/$',
        view=views.ProjectList.as_view(),
        name='project-list'
    ),
    url(
        regex=r'^projects/add/$',
        view=views.ProjectCreate.as_view(),
        name='project-add'
    ),
    url(
        regex=r'^projects/(?P<slug>[-\w]+)/$',
        view=views.ProjectDetail.as_view(),
        name='project-detail'
    ),
    url(
        regex=r'^projects/(?P<slug>[-\w]+)/edit/$',
        view=views.ProjectUpdate.as_view(),
        name='project-edit'
    ),
    url(
        regex=r'^projects/(?P<slug>[-\w]+)/delete/$',
        view=views.ProjectDelete.as_view(),
        name='project-delete'
    ),
    url(
        regex=r'^galleries/(?P<slug>[-\w]+)/items/$',
        view=views.ItemList.as_view(),
        name='item-list'
    ),
    url(
        regex=r'^galleries/items/add/$',
        view=views.ItemCreate.as_view(),
        name='item-add'
    ),
    url(
        regex=r'^galleries/items/(?P<slug>[-\w]+)/edit/$',
        view=views.ItemUpdate.as_view(),
        name='item-edit'
    ),
    url(
        regex=r'^galleries/items/(?P<slug>[-\w]+)/delete/$',
        view=views.ItemDelete.as_view(),
        name='item-delete'
    ),
    url(
        regex=r'^galleries/(?P<image_id>\d+)/add-product-image/$',
        view=views.AddProductImageToGallery.as_view(),
        name='add-product-image-to-gallery'
    ),
    url(
        regex=r'^galleries/(?P<image_id>\d+)/add-library-image/$',
        view=views.AddLibraryImageToGallery.as_view(),
        name='add-library-image-to-gallery'
    ),
    url(
        regex=r'^(?P<user_slug>[-\w]+)/galleries/$',
        view=views.GalleryList.as_view(),
        name='gallery-list'
    ),
]

nicolock/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^email-users/$',
        view=views.SendUserEmails.as_view(),
        name='email'
    ),
    url(
        regex=r'^$',
        view=views.UserList.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirect.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^account/$',
        view=views.UserUpdate.as_view(),
        name='update'
    ),
    url(
        regex=r'^~update/company-profile/$',
        view=views.CompanyProfileUpdate.as_view(),
        name='update-company-profile'
    ),
    url(
        regex=r'^company-profile/(?P<slug>[-\w]+)/$',
        view=views.CompanyProfileDetail.as_view(),
        name='company-profile-detail'
    ),
    url(
        regex=r'^manage-contractors/$',
        view=views.ManageContractors.as_view(),
        name='manage-contractors'
    ),
]

nicolock/core/models.py
from django.contrib.admin.models import LogEntry
from django.db.models.signals import post_save
from django.dispatch import receiver

from nicolock.users.models import User
from nicolock.taskapp.celery import notify_staff


@receiver(post_save, sender=LogEntry, dispatch_uid="site_change_notification")
def site_change_notification(sender, instance, created, **kwargs):
    pass
    # users = User.objects.filter(is_staff=True)
    # notify_staff.delay(instance, users)

nicolock/core/forms.py
from django import forms

from haystack.query import SearchQuerySet
from haystack.inputs import AutoQuery

from nicolock.products.models import Product, Color


class SearchForm(forms.Form):
    q = forms.CharField(required=False)

    def search(self, cleaned_data):
        return SearchQuerySet().filter(
            content=AutoQuery(cleaned_data['q']))


class QuoteForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()
    phone = forms.CharField()
    address = forms.CharField()
    city = forms.CharField()
    state = forms.CharField()
    postal_code = forms.CharField()
    project_type = forms.CharField()
    description = forms.CharField(widget=forms.Textarea)


class ContactForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()
    phone = forms.CharField()
    state = forms.CharField()
    postal_code = forms.CharField()
    subject = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)


class CustomerServiceRequestForm(forms.Form):
    install_date = forms.DateField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    address = forms.CharField(required=True)
    address2 = forms.CharField(required=False)
    city = forms.CharField(required=True)
    state = forms.CharField(required=True)
    postal_code = forms.CharField(required=True)
    phone = forms.CharField(required=True)
    email = forms.EmailField(required=True)

    pi_product = forms.ModelChoiceField(
        queryset=Product.objects.all(), empty_label="--Select--",
        required=False)
    pi_colors = forms.ModelChoiceField(
        queryset=Color.objects.all(), empty_label="--Select--",
        required=False)
    pi_square_feet = forms.CharField(required=False)
    pi_describe = forms.CharField(widget=forms.Textarea, required=False)
    pi_image1 = forms.ImageField(required=False)
    pi_image2 = forms.ImageField(required=False)
    pi_image3 = forms.ImageField(required=False)

    # ii_installed
    ii_purchased = forms.CharField(required=False)
    ii_name = forms.CharField(required=False)
    ii_address = forms.CharField(required=False)
    ii_address2 = forms.CharField(required=False)
    ii_city = forms.CharField(required=False)
    ii_state = forms.CharField(required=False)
    ii_postal_code = forms.CharField(required=False)
    ii_phone = forms.CharField(required=False)
    ii_cell = forms.CharField(required=False)
    ii_email = forms.EmailField(required=False)

nicolock/landing/forms.py
from django import forms

from .models import Template
from nicolock.menus.models import Menu
from nicolock.core.utils import get_url_choices


class TemplateAdminForm(forms.ModelForm):

    class Meta:
        model = Template
        fields = '__all__'
        widgets = {
            'top_left_button_one_link': forms.Select(),
            'top_right_button_one_link': forms.Select(),
            'top_right_button_two_link': forms.Select(),
            'top_right_button_three_link': forms.Select(),
            'bottom_left_button_one_link': forms.Select(),
            'bottom_left_button_two_link': forms.Select(),
            'bottom_right_button_one_link': forms.Select(),
            'button_link': forms.Select(),
        }

    def __init__(self, *args, **kwargs):
        super(TemplateAdminForm, self).__init__(*args, **kwargs)
        url_choices = [('', '--Select One--')] + get_url_choices()
        self.fields['top_left_button_one_link'].widget.choices = url_choices
        self.fields['top_right_button_one_link'].widget.choices = url_choices
        self.fields['top_right_button_two_link'].widget.choices = url_choices
        self.fields['top_right_button_three_link'].widget.choices = url_choices
        self.fields['bottom_left_button_one_link'].widget.choices = url_choices
        self.fields['bottom_left_button_two_link'].widget.choices = url_choices
        self.fields['bottom_right_button_one_link'].widget.choices = url_choices
        self.fields['button_link'].widget.choices = url_choices

nicolock/menus/forms.py
from django import forms
from django.contrib.admin.widgets import FilteredSelectMultiple

from .models import ChildItem, Item, Menu
from .widgets import ListTextWidget


class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = '__all__'
        widgets = {
            'url': ListTextWidget()
        }


class ChildItemForm(forms.ModelForm):

    class Meta:
        model = ChildItem
        fields = '__all__'
        widgets = {
            'url': ListTextWidget()
        }


class MenuForm(forms.ModelForm):

    class Meta:
        model = Menu
        fields = '__all__'
        widgets = {
            'url': FilteredSelectMultiple('urls', is_stacked=False)
        }

nicolock/products/forms.py
from django import forms

from .models import Image


class ProductImageForm(forms.Form):
    image = forms.IntegerField()

    def is_valid(self):
        valid = super(ProductImageForm, self).is_valid()
        if valid:
            self.image_object = Image.objects.filter(
                id=self.cleaned_data['image']).first()
        return valid

nicolock/users/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import User, CompanyProfile


class SignupForm(forms.Form):
    """
    Django allauth automatically makes this form inherit from
    allauth.account.forms.SignupForm to prevent a circular import. I only need
    to add additional fields. Email and password will be taken care of.
    """
    name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': _('Name')}))
    postal_code = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': _('Zipcode')}))
    user_type = forms.ChoiceField(
        choices=User.USER_TYPES, widget=forms.RadioSelect)

    field_order = [
        'user_type',
        'name',
        'email',
        'password',
        'postal_code'
    ]

    def signup(self, request, user):
        user.postal_code = self.cleaned_data['postal_code']
        user.user_type = self.cleaned_data['user_type']
        user.email = self.cleaned_data['email'].lower()
        user.save()


class ContractorSearchForm(forms.Form):
    postal_code = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': _('Zipcode')}))

    def search(self, cleaned_data):
        profiles = CompanyProfile.objects.filter(
            user__user_type='contractor', 
            user__postal_code=cleaned_data['postal_code'])
        return profiles.exclude(
            longitude__isnull=True, 
            latitude__isnull=True)


class SendEmailForm(forms.Form):
    subject = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': _('Subject')}))
    message = forms.CharField(widget=forms.Textarea)
    users = forms.ModelMultipleChoiceField(label="To",
                                           queryset=User.objects.all(),
                                           widget=forms.SelectMultiple())


class UserUpdateForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': _('Name')}))
    email = forms.EmailField(
        widget=forms.TextInput(attrs={'placeholder': _('Email')}))
    postal_code = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': _('Zipcode')}))
    new_password = forms.CharField(
        required=False,
        widget=forms.PasswordInput(attrs={'placeholder': _('Zipcode')}))
    confirm_new_password = forms.CharField(
        required=False,
        widget=forms.PasswordInput(attrs={'placeholder': _('Zipcode')}))

nicolock/templates/components/add_gallery_modal.html
{% if user_galleries %}
  <div
    id="add-image-to-gallery"
    data-galleries='{{ user_galleries_json }}'
    ></div>
{% else %}
  <h4 class="title">Add To Gallery</h4>
  <p class="paragraph">You currently don't have any galleries. Click <a class="link neutral-0" href="{% url 'galleries:gallery-add' %}?from={{ request.path|urlencode }}">here</a> to add a gallery.</p>
{% endif %}

nicolock/templates/components/color_pattern_modal.html
<div class="product-modal-view">
  <div class="product-modal-content">
    <img class="product-modal-image" src="" />
  </div>
  <div class="product-modal-footer">
    <div class="modal-icon-wrap">
      <span class="download-icon">
        {% include "components/icons/icon-download.svg" %}
      </span>
      <span class="print-icon">
        {% include "components/icons/icon-print.svg" %}
      </span>
      <!-- <span class="gallery-icon"></span> -->
    </div>
    <h6 class="title"></h6>
    <div class="paragraph"></div>
  </div>
</div>

nicolock/templates/components/desktopMenu.html
<div class="newsletter-wrap">
  <!-- Begin MailChimp Signup Form -->
  <form action="https://nicolock.us1.list-manage.com/subscribe/post?u=db01cd58fee280357dbbc4074&amp;id=2eaa006ed6" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
      <div class="input-group">
        <input type="email" value="" name="EMAIL" class="input required email" id="mce-EMAIL" placeholder="SIGN UP FOR OUR NEWSLETTER">
      </div>
      <div id="mce-responses" class="clear">
        <div class="response" id="mce-error-response" style="display:none"></div>
        <div class="response" id="mce-success-response" style="display:none"></div>
      </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
      <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_db01cd58fee280357dbbc4074_2eaa006ed6" tabindex="-1" value=""></div>
      <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn neutral-4 hollow">
    </div>
  </form>
  <!--End mc_embed_signup-->
</div>

nicolock/templates/components/download_modal.html
<h4 class="title text--center push--bottom">Download</h4>
<p class="paragraph">Select items you would like to<br />download.</p>
<div class="download-items">
  {% for file in product.files.all %}
    <div class="input-group">
      <label class="checkbox">
        <input type="checkbox" id="file{{ file.id }}" name="file{{ file.id }}" value="{{ file.id }}">
        <span></span>
        {{ file.name }}
      </label>
    </div>
  {% endfor %}
</div>
<button class="btn btn-md neutral-0" id="download-specs">DOWNLOAD</button>

nicolock/templates/components/dynamic_menu.html
{% if menus.section_one %}
  <ul class="misc-menu-parent">
    {% for item in menus.section_one %}
      <li class="misc-menu-category{% if item.has_children %} has-children{% endif %}">
        <a class="link neutral-0 parent" href="{{ item.url }}">{{ item.label }}</a>
        {% for child in item %}
          {% if forloop.first %}
            <ul class="misc-menu-child">
          {% endif %}
          <li>
            <a class="link neutral-1 child" href="{{ child.url }}">{{ child.label }}</a>
          </li>
          {% if forloop.last %}
            </ul>
          {% endif %}
        {% endfor %}
      </li>
    {% endfor %}
  </ul>
{% endif %}
{% if menus.section_two %}
  <ul class="misc-menu-parent">
    {% for item in menus.section_two %}
      <li class="misc-menu-category{% if item.has_children %} has-children{% endif %}">
        <a class="link neutral-0 parent" href="{{ item.url }}">{{ item.label }}</a>
        {% for child in item %}
          {% if forloop.first %}
            <ul class="misc-menu-child">
          {% endif %}
          <li>
            <a class="link neutral-1 child" href="{{ child.url }}">{{ child.label }}</a>
          </li>
          {% if forloop.last %}
            </ul>
          {% endif %}
        {% endfor %}
      </li>
    {% endfor %}
  </ul>
{% endif %}
{% if menus.section_three %}
  <ul class="misc-menu-parent">
    {% for item in menus.section_three %}
      <li class="misc-menu-category{% if item.has_children %} has-children{% endif %}">
        <a class="link neutral-0 parent" href="{{ item.url }}">{{ item.label }}</a>
        {% for child in item %}
          {% if forloop.first %}
            <ul class="misc-menu-child">
          {% endif %}
          <li>
            <a class="link neutral-1 child" href="{{ child.url }}">{{ child.label }}</a>
          </li>
          {% if forloop.last %}
            </ul>
          {% endif %}
        {% endfor %}
      </li>
    {% endfor %}
  </ul>
{% endif %}

nicolock/templates/components/forgotModal.html
<div class="modal-view">
  <div class="modal-header">
    <h4 class="title">Password Reset</h4>
  </div>

  <div class="modal-content">
    <form class="form" method="post" action="{% url 'account_reset_password' %}">
      {% csrf_token %}
      <div class="input-group">
        <p class="paragraph">Forgotten your password? Enter your e-mail address below, and we'll send you an e-mail allowing you to reset it.</p>
      </div>
      <div class="input-group">
        <input class="input" name="email" placeholder="E-mail address" type="email" required="" />
      </div>
      <button class="btn btn-md neutral-0" type="submit">RESET MY PASSWORD</button>
      <div class="input-group">
        <p class="paragraph"><a class="link neutral-0 modal-transition" href="" data-authentication="login">Cancel</a></p>
      </div>
    </form>
  </div>

  <div class="modal-footer">
  </div>
</div>

nicolock/templates/components/header.html
{% load staticfiles i18n %}
<header>
  <div class="header-container-top">
      <div class="landing-links">
        <a class="link" href="{% url 'pages' 'homeowner' %}">Homeowners</a>
        <a class="link" href="{% url 'pages' 'contractor' %}">Contractors</a>
        <a class="link" href="{% url 'pages' 'retail' %}">Dealers</a>
        <!-- <a class="link neutral-0" href="{% url 'pages' 'commercial' %}">Commercial</a> -->
      </div>
      <div class="find-links-container">
        <div class="find-links">
          <a class="link neutral-0" href="{% url 'find-contractors' %}">Find A Contractor</a> |
          <a class="link neutral-0" href="{% url 'dealers:list' %}">Find A Dealer</a>
        </div>
        <span class="telephone">631.669.0700</span>
      </div>
    </div>
    <div class="header-container-bottom">
      <a href="/"><img class="logo" src="{% static 'images/logo.png' %}" /></a>
      <div>
        <nav>
          {% include "./icons/icon-close.svg" %}
          <a class="link neutral-0" href="{% url 'library:list' %}">Get Inspired</a>
          <a class="link neutral-0" href="/products">Products</a>
          <a class="link neutral-0" href="{% url 'events:list' %}">Events</a>
          <a class="link neutral-0" href="">Downloads</a>
          <a class="link neutral-0" href="{% url 'core:contact' %}">Contact</a>
          {% if request.user.is_authenticated %}
          <a class="link neutral-0" href="{% url 'users:update' %}">{% trans "My Account" %}</a>
          <a class="link neutral-0" href="{% url 'account_logout' %}">{% trans "Logout" %}</a>
          {% else %}
          <a class="btn btn-sm neutral-0 modal-trigger" href="">{% trans "Login" %}</a>
          {% endif %}
        </nav>
        <span class="icon-menu nav-trigger">
            <span class="menu-bar"></span>
            <span class="menu-bar"></span>
            <span class="menu-bar"></span>
            <span class="menu-bar"></span>
          </span>
      </div>
  </div>
</header>

nicolock/templates/components/latest_videos.html
{% load staticfiles %}
<div class="section-2">
  <h4 class="title">Latest<br />Videos<br /><br /></h4>
  {% for video in videos %}
    <a class="link" href="{{ video.get_absolute_url }}">
      <div class="like-block pad-half--bottom">
        <div class="pad-half--sides thumbnail-wrapper">
          <img src="{{ video.thumbnail_url }}">
        </div>
        <div class="pad-half--sides info-wrapper">
          <p class="info">{{ video.name }}</p>
        </div>
      </div>
    </a>
  {% endfor %}
</div>

nicolock/templates/components/related_video_modal.html
<iframe class="related-video-iframe video-iframe" src="" frameborder="0" allowfullscreen></iframe>
  